sudo: false
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.php7.all = 1' >> /etc/hhvm/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi

script: bin/kahlan --coverage=3 --clover=clover.xml --reporter=verbose

after_success:
  - "if [ $(phpenv version-name) = '7.3' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.3' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    - secure: m8BRKwDomCXi5fcHNP2Nbsg7x40+b6Z1yIBEMDOvRXeRCHAWe7rUpdSjnhnEoxgJh3JqOe/2YsqIHlwezlcauS5tfa7vZVgj/bvW+h9PHQPxGVRb0nmuUUzgT0rQ0UhK9dbWWo+BcvW1Ol9CSeD0+LURVL12CTsBsf2AuxtJZNK85AwgkU5Ee7oUhhAW52EnxfGw/aaz2JYQJhiswIltkU7LyJMkd5hklLfxP06g8twhu2tog9C6+mZIqlPwNydqjepq1QKI6YuGVJn+/WFT4OcWlozvk7Bv9Oy2S2dDVFdZuwHGNul8n+fAQoJPFfB9SzrPVK38RoXc+GXec/Je6UoOG+PED4u2+xAh3Pezl7O+Lhakdf+aIF8yfzYpy5i+EtDF8j46TTHjvoN+/p7W+j64S7MD9aRR4/+WLsOvPGvEkSWVFxtpsFKHVa1such0gVKLyS88uIeW9rM2NFHqoOObsUxrHLxe6FEFw02NMMRns3J/Oln8YV2NLOrLbFELGyUO9BzLEHCZMZ2Kf08h+DO2Aj1iKi99urTLcGhMMQSFVtMyF+/oi3MF3C9lKRYVa9vFpyt+QY/swzrNfR5ur7nks7lvKBjDegyq8AYN0VkhAQLbyuWKgMM0xDthLYEacJv7GSWshlbUWXZvit1NXi3C74K4JlBcolsCvLrmDN4=
