language: php

php:
  - 7.4
  - 8.1

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-interaction

script: bin/kahlan --coverage=3 --clover=clover.xml --reporter=verbose

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    - secure: IV3svZ2jJQBA7ElFwsX8Bp+poul3BUG9LFJ/BUH2TmH1+JLdwcaL3hB+Ua2MErp0FWuRlNAm7aLrMMZYEeqFbhlRNvM7EuhzV3gmS7yJ60QpLPj72HCX6x4/+SWIDf5bK4mD78UWL2nAd/f1v8hrZEdfSPjmATOCdobRMHhMMj/HVc2UHQGeUko5a5uUsakzpuNARMeCrBRtu5ps4bnIwF9kS5yuqIeCjHDQJh9StHtf/t3umxFfEzVyD0SmdJJn/iC95xnD+Ca+EaoYElpwLC5jcbjzDF2yItcp1FYGGTYPXXNWkJ2aI3KF6L/+uvBG1uc58v/sfvK/m3i70JlIq01jE8rpFCVqM1O9zsMbzFl935RzV9v4ti9MkfWuW9fXkJJFZ+h+s2fnA3enXxkUySlh8L97DHdz7zzDzRwhz2GIflMF6vcjSBqP83N+NwYmQ/dZty5j1QsIBTqL8sa9Enz4E+oi78v9rWxXGoeYImlRgcVbrgIFlIltmbRrcPmKkRrN0M/3ulsB+UWz0V8KcvxEGBZEJCgXcT8YRSzfsD2nI7Eg41kOjyrUbApSNdD7AcU5Y2Jhue+AwP2klQeelXqrzoPlXoIp43rkiRR1Uz/7dgXXOY0RKAujIsssQ2sAYRAxMrAe9NhwJ4XtEgjI8kSq+GdKliLYz7+f6L0h5Fo=
